### ISSUE TITLE
Issue with Github Actions, using AUTODOWNLOAD=ON for now

### ISSUE THREAD

**Issue by Abi1024** [GraphStreamingProject/GraphZeppelin#21]
For some reason, boost serialization component binaries are built to a location that is currently not cached by GithubActions. Until we fix this issue, we are using AUTODOWNLOAD=ON for cmake. This is a hacky solution that is fine for now but should be fixed later, probably by either myself or Victor.

**Comment by etwest** [comment]
With recent cmake changes -DAUTODOWNLOAD is no longer necessary
