### ISSUE TITLE
USE_NATIVE_F is a mess

### ISSUE THREAD

**Issue by Victor-C-Zhang** [GraphStreamingProject/GraphZeppelin#37]
Currently, we're using 32 bit types for `bucket_a` and `bucket_c` so in theory we should be able to support only 32-bit numbers of nodes. But we use type `Node = uint64_t` for everything else, which means we should instead be using 64 bits for `bucket_a`. So far we haven't noticed anything wrong because our tests are small, but this *must* be fixed before we can do any large scale testing.

**Comment by etwest** [comment]
Is this still an issue?

**Comment by Victor-C-Zhang** [comment]
Yes, we're not using the `node_t` types. We use type `Node` instead, which doesn't change when we want to use 32-bit types. It's not an immediate problem, since the house of cards is set up exactly the way we want it, but it's an issue for the future.
